In [2]:
import pandas as pd
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [3]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [5]:
print(df.groupby("Department"))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001C9179E1A90>

In [8]:
df.groupby("Department")["Salary"].mean().astype(int)

Department
HR           87
IT           81
Marketing    90
Sales        77
Name: Salary, dtype: int64

In [9]:
df.groupby("Department")["Salary"].sum()

Department
HR           175
IT           163
Marketing    180
Sales        155
Name: Salary, dtype: int64

In [10]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
Marketing    2
Sales        2
Name: Salary, dtype: int64

In [11]:
df.groupby("Department")["Salary"].min()

Department
HR           85
IT           78
Marketing    88
Sales        75
Name: Salary, dtype: int64

In [12]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [13]:
df.groupby(["Department","Team"])["Salary"].mean()

Department  Team
HR          A       87.5
IT          B       81.5
Marketing   C       90.0
Sales       D       77.5
Name: Salary, dtype: float64

In [14]:
df.groupby("Department")["Salary"].agg(["mean","max","count","min","sum"])

            mean  max  count  min  sum
Department
HR          87.5   90      2   85  175
IT          81.5   85      2   78  163
Marketing   90.0   92      2   88  180
Sales       77.5   80      2   75  155

In [24]:
df.groupby("Team")["Salary"].agg(
    avg_score="mean",
    high_score="max"
)

      avg_score  high_score
Team
A          87.5          90
B          81.5          85
C          90.0          92
D          77.5          80

In [26]:
df.groupby("Team").agg({
    "Salary": "mean",
    "Age": "max"
})

      Salary  Age
Team
A       87.5   25
B       81.5   30
C       90.0   28
D       77.5   27

In [29]:
 df.groupby("Team")["Salary"].transform("mean")

0    87.5
1    87.5
2    81.5
3    81.5
4    90.0
5    90.0
6    77.5
7    77.5
Name: Salary, dtype: float64

In [31]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [32]:
df.groupby("Team").filter(lambda x: x["Salary"].mean() > 80)

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0

In [34]:
df["Avg Salary"]=df["Salary"].mean()

In [35]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg  Avg Salary
0         HR    A      M      85   23 2020-01-10      87.5      84.125
1         HR    A      F      90   25 2020-02-15      87.5      84.125
2         IT    B      M      78   30 2021-03-20      81.5      84.125
3         IT    B      F      85   22 2021-04-10      81.5      84.125
4  Marketing    C      M      92   28 2020-05-30      90.0      84.125
5  Marketing    C      F      88   26 2020-06-25      90.0      84.125
6      Sales    D      M      75   21 2021-07-15      77.5      84.125
7      Sales    D      F      80   27 2021-08-01      77.5      84.125