In [1]:
import pandas as pd

In [2]:
df=pd.Series([1,2,3,4,5,6])

In [3]:
df

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
df[0]

np.int64(1)

In [58]:
dict={
    "First Name":["Yash","Pratham","Harsh","Neel","Bhaumik"],
    "Score":[90,47,89,67,78],
    "Age":[21,22,21,20,20],
    "Salary":[34000,7000,3000,4500,8700]
}

In [59]:
dict

{'First Name': ['Yash', 'Pratham', 'Harsh', 'Neel', 'Bhaumik'],
 'Score': [90, 47, 89, 67, 78],
 'Age': [21, 22, 21, 20, 20],
 'Salary': [34000, 7000, 3000, 4500, 8700]}

In [62]:
df=pd.DataFrame(dict)

In [63]:
df

  First Name  Score  Age  Salary
0       Yash     90   21   34000
1    Pratham     47   22    7000
2      Harsh     89   21    3000
3       Neel     67   20    4500
4    Bhaumik     78   20    8700

In [65]:
df["First Name"]

0       Yash
1    Pratham
2      Harsh
3       Neel
4    Bhaumik
Name: First Name, dtype: object

In [66]:
df[["Name","Age"]]

KeyError: "['Name'] not in index"

In [68]:
df.loc[0]

First Name     Yash
Score            90
Age              21
Salary        34000
Name: 0, dtype: object

In [69]:
df.loc[0:2]

  First Name  Score  Age  Salary
0       Yash     90   21   34000
1    Pratham     47   22    7000
2      Harsh     89   21    3000

In [70]:
df.iloc[0:3,1:3]

   Score  Age
0     90   21
1     47   22
2     89   21

In [71]:
df

  First Name  Score  Age  Salary
0       Yash     90   21   34000
1    Pratham     47   22    7000
2      Harsh     89   21    3000
3       Neel     67   20    4500
4    Bhaumik     78   20    8700

In [72]:
df.loc[0,"First Name"]

'Yash'

In [73]:
df.iloc[0,0]

'Yash'

In [43]:
df.iat[0,0]

'Yash'

In [74]:
df[df["Age"]>21]

  First Name  Score  Age  Salary
1    Pratham     47   22    7000

In [75]:
df[df["Age"]==21]

  First Name  Score  Age  Salary
0       Yash     90   21   34000
2      Harsh     89   21    3000

In [76]:
df2=df[(df["Age"]==21) | (df["Salary"]==34000)].copy()

In [77]:
df2

  First Name  Score  Age  Salary
0       Yash     90   21   34000
2      Harsh     89   21    3000

In [78]:
df2.reset_index()

   index First Name  Score  Age  Salary
0      0       Yash     90   21   34000
1      2      Harsh     89   21    3000

In [79]:
df2.dropna()

  First Name  Score  Age  Salary
0       Yash     90   21   34000
2      Harsh     89   21    3000

In [80]:
df.query("Age > 20 and Salary>100")

  First Name  Score  Age  Salary
0       Yash     90   21   34000
1    Pratham     47   22    7000
2      Harsh     89   21    3000

In [81]:
df.query("`First Name`=='Yash'")

  First Name  Score  Age  Salary
0       Yash     90   21   34000

In [84]:
age_limit=20
df.query("Age > @age_limit")

  First Name  Score  Age  Salary
0       Yash     90   21   34000
1    Pratham     47   22    7000
2      Harsh     89   21    3000

In [85]:
df.query("20<Age<25")

  First Name  Score  Age  Salary
0       Yash     90   21   34000
1    Pratham     47   22    7000
2      Harsh     89   21    3000