In [2]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [4]:
df.melt(id_vars=["Name"],value_vars=["Math","Science","English"],var_name="Subject",value_name="Marks")

      Name  Subject  Marks
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [5]:
dict={
    "Name":["Alice","Alice","Alice","Bob","Bob"],
    "Subject":["Math","Math","Science","Math","Math"],
    "Score":[85,80,90,78,82]
}

In [6]:
df1=pd.DataFrame(dict)

In [7]:
df1

    Name  Subject  Score
0  Alice     Math     85
1  Alice     Math     80
2  Alice  Science     90
3    Bob     Math     78
4    Bob     Math     82