In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})
 
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees,departments,on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [8]:
pd.merge(employees,departments,on="DeptID",how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [9]:
pd.merge(employees,departments,on="DeptID",how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [10]:
pd.merge(employees,departments,on="DeptID",how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [11]:
pd.concat([employees,departments])

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10          NaN
1    2.0      Bob      20          NaN
2    3.0  Charlie      30          NaN
0    NaN      NaN      10           HR
1    NaN      NaN      20  Engineering
2    NaN      NaN      40    Marketing

In [12]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})
 
pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [13]:
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})
 
pd.concat([df1, df2])

    ID  Score
0  1.0    NaN
1  2.0    NaN
0  NaN   90.0
1  NaN   80.0

In [14]:
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})
 
pd.concat([df1, df2], axis=1)

   ID  Score
0   1     90
1   2     80

In [15]:
pd.concat([employees,departments], axis=1)

   EmpID     Name  DeptID  DeptID     DeptName
0      1    Alice      10      10           HR
1      2      Bob      20      20  Engineering
2      3  Charlie      30      40    Marketing

In [31]:
df11=pd.concat([employees,departments]).copy()

In [32]:
df11

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10          NaN
1    2.0      Bob      20          NaN
2    3.0  Charlie      30          NaN
0    NaN      NaN      10           HR
1    NaN      NaN      20  Engineering
2    NaN      NaN      40    Marketing

In [33]:
df11.isnull()

   EmpID   Name  DeptID  DeptName
0  False  False   False      True
1  False  False   False      True
2  False  False   False      True
0   True   True   False     False
1   True   True   False     False
2   True   True   False     False

In [34]:
df11.isnull().sum()

EmpID       3
Name        3
DeptID      0
DeptName    3
dtype: int64

In [35]:
df11.dropna()

Empty DataFrame
Columns: [EmpID, Name, DeptID, DeptName]
Index: []

In [36]:
df11

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10          NaN
1    2.0      Bob      20          NaN
2    3.0  Charlie      30          NaN
0    NaN      NaN      10           HR
1    NaN      NaN      20  Engineering
2    NaN      NaN      40    Marketing

In [37]:
df11.fillna(0)

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10            0
1    2.0      Bob      20            0
2    3.0  Charlie      30            0
0    0.0        0      10           HR
1    0.0        0      20  Engineering
2    0.0        0      40    Marketing